sites:
  brightonfemcol:
    instances:
    - live
    configs:
    - type: nginx
      application: django
      parent: secure
    - type: uwsgi
      config:
        processes: 2
        threads: 4
      env:
        DJANGO_SETTINGS_MODULE: brightonfemcol.settings.production
        DJANGO_DB_PASSWORD: "i7sdf6bsf3twrjyfov$52%"
types:
  nginx: /etc/nginx/servers/{name}_{instance}.conf
  uwsgi: /srv/{name}/{instance}/uwsgi.ini
